### ISSUE TITLE
onvif_client_123 receives response "401 unauthorized"

### ISSUE THREAD

**Issue by mkaufer** [lankahsu520/utilx9#1]
Hi, I am trying to use Onvif to connect to a device. I have downloaded everything needed and added the patches to mxml. I have updated the onvif_client_123.c with the ipaddress, port, username and password of the device. The following functions work fine: qtask_GetCapabilities, qtask_GetHostname, qtask_GetServices, however the other functions return something similar to this qtask_GetDeviceInformation:213 - No support !!! (http://192.168.2.113:80/onvif/device_service). I set the debug level higher and was able to get some more helpful logs. All of the functions other than the ones listed above fail with HTTP ERROR 401 Unauthorized. Looking over the soap request everything seems to be correct so I am unsure why authorization is failing. Any help with resolving this issue would be greatly appreciated, thanks.

**Comment by lankahsu520** [comment]
Please update your codes and check [helper_ONVIF.md](https://github.com/lankahsu520/HelperX/blob/master/helper_ONVIF.md)

You can use "ONVIF Device Manage" to check first.
And
$ ./onvif_client_123 -d3 -i 192.168.50.21 -p 80 -u admin -s admin -e "/onvif/device_service" -m "/onvif/media_service"

**Comment by lankahsu520** [comment]
my GetDeviceInformation
```
[504239/504240] soap_http_access:230 - (request: <?xml version='1.0' encoding='utf-8'?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema"><SOAP-ENV:Body><tds:GetDeviceInformation /></SOAP-ENV:Body><SOAP-ENV:Header><Security SOAP-ENV:mustUnderstand="1" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2022-11-10T16:46:37.000Z</Created><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">x0BbkmDhBrVrAGMEHDVvdG8E6OI=</Nonce><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">tfQNGKukUm+ri8jqMhRzF/5GLq8=</Password></UsernameToken></Security></SOAP-ENV:Header></SOAP-ENV:Envelope>
)
[504239/504240] http_request_soap:248 - enter (soap_req->h_action: (null))
*   Trying 192.168.50.21:80...
* Connected to 192.168.50.21 (192.168.50.21) port 80 (#0)
> POST /onvif/device_service HTTP/1.1
Host: 192.168.50.21
Accept: */*
Content-Type: application/soap+xml; charset=utf-8
Accept-Encoding: gzip, deflate
Content-Length: 1012

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/soap+xml; charset=utf-8
< Connection: close
< Content-Length: 621
<
* Closing connection 0
[504239/504240] http_request_soap:325 - ret: 0,
[504239/504240] soap_http_access:236 - (response: <?xml version="1.0" encoding="utf-8" standalone="yes" ?><s:Envelope xmlns:sc="http://www.w3.org/2003/05/soap-encoding" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema"><s:Header/><s:Body><tds:GetDeviceInformationResponse><tds:Manufacturer>General</tds:Manufacturer><tds:Model>IP Camera</tds:Model><tds:FirmwareVersion>2.400.0000.16.R, Build Date 2017-08-31</tds:FirmwareVersion><tds:SerialNumber>2L066D7PAG00031</tds:SerialNumber><tds:HardwareId>1.00</tds:HardwareId></tds:GetDeviceInformationResponse></s:Body></s:Envelope>)
[504239/504240] qtask_GetDeviceInformation:187 - (gid:769.0, Manufacturer: General)
[504239/504240] qtask_GetDeviceInformation:188 - (gid:769.0, Model: IP Camera)
[504239/504240] qtask_GetDeviceInformation:189 - (gid:769.0, FirmwareVersion: 2.400.0000.16.R, Build Date 2017-08-31)
[504239/504240] qtask_GetDeviceInformation:190 - (gid:769.0, SerialNumber: 2L066D7PAG00031)
[504239/504240] qtask_GetDeviceInformation:191 - (gid:769.0, HardwareId: 1.00)
```

**Comment by lankahsu520** [comment]
From my experience, try to remove user/password on GetDeviceInformation.
Some devices need user/password on some request but not on others.

**Comment by mkaufer** [comment]
Thank you for the quick response! 
This is my ./wsdiscovery_123 -d 3
[1403891/1403892] chainX_udp_bind:2113 - bind ... (239.255.255.250:3702)
[1403891/1403892] chainX_thread_handler_udp:3101 - udp-bind ok !!! (239.255.255.250:3702, dbg: 4, net_status: 1, sockfd: 3, net_security: 0)
[1403891/1403891] wsdiscovery_uuid_gen:293 - (messageid: uuid:1A38B881-209B-4D8C-bBA6-AE5E5F1DB5A1)
[1403891/1403891] chainX_multi_sender:3027 - SOCKETX_SENDTO ... (:3702)
[1403891/1403891] wsdiscovery_uuid_gen:293 - (messageid: uuid:1A38B881-209B-4D8C-bBA6-AE5E5F1DB5A1)
[1403891/1403891] chainX_multi_sender:3027 - SOCKETX_SENDTO ... (:3702)
[1403891/1403891] wsdiscovery_uuid_gen:293 - (messageid: uuid:7D4FAF2D-5568-45EA-8DC5-C35209E5142B)
[1403891/1403891] chainX_multi_sender:3027 - SOCKETX_SENDTO ... (:3702)
[1403891/1403891] wsdiscovery_uuid_gen:293 - (messageid: uuid:7D4FAF2D-5568-45EA-8DC5-C35209E5142B)
[1403891/1403891] chainX_multi_sender:3027 - SOCKETX_SENDTO ... (:3702)
[1403891/1403891] wsdiscovery_uuid_gen:293 - (messageid: uuid:37AE3253-6087-4124-8653-5240197B23BC)
[1403891/1403891] chainX_multi_sender:3027 - SOCKETX_SENDTO ... (:3702)
[1403891/1403891] wsdiscovery_uuid_gen:293 - (messageid: uuid:37AE3253-6087-4124-8653-5240197B23BC)
[1403891/1403891] chainX_multi_sender:3027 - SOCKETX_SENDTO ... (:3702)

It just continues this as long as I let it run and I am confused as to why this may be happening. Could it be an issue with my network? Currently the network on my machine is set up as a bridge so I can have virtual machines running and have them connected to the internet. I have a windows machine where I am running Onvif Device Manager and it works perfectly but that machine's network is a simple ethernet connection.

This is my ./onvif_client_123 edited with having no user/password for GetDeviceInformation.
[1404108/1404108] main:784 - Start !!! (192.168.2.113:80, admin:637d63, device_url_path: /onvif/device_service, media_url_path: /onvif/media_service)
[1404108/1404109] qtask_GetCapabilities:131 - (gid:769.0, tt:Device: http://192.168.2.113:80/onvif/device_service)
[1404108/1404109] qtask_GetCapabilities:131 - (gid:769.0, tt:Events: http://192.168.2.113:80/onvif/event_service)
[1404108/1404109] qtask_GetCapabilities:131 - (gid:769.0, tt:Imaging: http://192.168.2.113:80/onvif/image_service)
[1404108/1404109] qtask_GetCapabilities:131 - (gid:769.0, tt:Media: http://192.168.2.113:80/onvif/media_service)
[1404108/1404109] qtask_GetCapabilities:110 - (gid:769.0, tt:DeviceIO: http://192.168.2.113:80/onvif/deviceio_service)

mxml: Mismatched close tag </body> under parent <hr> on line 15.
[1404108/1404109] qtask_GetDeviceInformation:197 - No support !!! (http://192.168.2.113:80/onvif/device_service)

[1404108/1404109] qtask_GetHostname:229 - (gid:769.0, FromDHCP: true, Name: onyx-p1)

[1404108/1404109] qtask_GetServices:346 - (gid:769.0, Namespace: http://www.onvif.org/ver10/device/wsdl)
[1404108/1404109] qtask_GetServices:347 - (gid:769.0, XAddr: http://192.168.2.113:80/onvif/device_service)
[1404108/1404109] qtask_GetServices:346 - (gid:769.0, Namespace: http://www.onvif.org/ver10/deviceIO/wsdl)
[1404108/1404109] qtask_GetServices:347 - (gid:769.0, XAddr: http://192.168.2.113:80/onvif/deviceio_service)
[1404108/1404109] qtask_GetServices:346 - (gid:769.0, Namespace: http://www.onvif.org/ver20/media/wsdl)
[1404108/1404109] qtask_GetServices:347 - (gid:769.0, XAddr: http://192.168.2.113:80/onvif/media_service)
[1404108/1404109] qtask_GetServices:346 - (gid:769.0, Namespace: http://www.onvif.org/ver10/media/wsdl)
[1404108/1404109] qtask_GetServices:347 - (gid:769.0, XAddr: http://192.168.2.113:80/onvif/media_service)
[1404108/1404109] qtask_GetServices:346 - (gid:769.0, Namespace: http://www.onvif.org/ver20/imaging/wsdl)
[1404108/1404109] qtask_GetServices:347 - (gid:769.0, XAddr: http://192.168.2.113:80/onvif/image_service)
[1404108/1404109] qtask_GetServices:346 - (gid:769.0, Namespace: http://www.onvif.org/ver10/events/wsdl)
[1404108/1404109] qtask_GetServices:347 - (gid:769.0, XAddr: http://192.168.2.113:80/onvif/event_service)

mxml: Mismatched close tag </body> under parent <hr> on line 15.
[1404108/1404109] qtask_GetScopes:403 - No support !!! (http://192.168.2.113:80/onvif/device_service)

mxml: Mismatched close tag </body> under parent <hr> on line 15.
[1404108/1404109] qtask_GetNetworkInterfaces:315 - No support !!! (http://192.168.2.113:80/onvif/device_service)

mxml: Mismatched close tag </body> under parent <hr> on line 15.
[1404108/1404109] qtask_GetProfiles:444 - No support !!! (http://192.168.2.113:80/onvif/media_service)

mxml: Mismatched close tag </body> under parent <hr> on line 15.
[1404108/1404109] qtask_GetStreamUri:528 - No support !!! (http://192.168.2.113:80/onvif/media_service)

mxml: Mismatched close tag </body> under parent <hr> on line 15.
[1404108/1404109] qtask_GetSnapshotUri:486 - No support !!! (http://192.168.2.113:80/onvif/media_service)

**Comment by lankahsu520** [comment]
There are some problems with the response.

Maybe you need to run ./wsdiscovery_123 -d 4
to get more debug messges such as

```log
soap_http_access:230 - (request:
soap_http_access:236 - (response:
```

I also tried to modify my onvif_client_123.c, just query GETDEVICEINFORMATION
```c
		//qtask_push(769, 0, SOAP_ACTION_ID_DEVICE_GETCAPABILITIES);
		qtask_push(769, 0, SOAP_ACTION_ID_DEVICE_GETDEVICEINFORMATION);
		//qtask_push(769, 0, SOAP_ACTION_ID_DEVICE_GETHOSTNAME);
		//qtask_push(769, 0, SOAP_ACTION_ID_DEVICE_GETSERVICES);
		//qtask_push(769, 0, SOAP_ACTION_ID_DEVICE_GETSCOPES);
		//qtask_push(769, 0, SOAP_ACTION_ID_DEVICE_GETNETWORKINTERFACES);

		//qtask_push(769, 0, SOAP_ACTION_ID_MEDIA_GETPROFILES);
		//qtask_push(769, 0, SOAP_ACTION_ID_MEDIA_GETSTREAMURI);

		//qtask_push(769, 0, SOAP_ACTION_ID_MEDIA_GETSNAPSHOTURI);
```
#### A. without pass
```log
$ ./onvif_client_123 -d4 -i 192.168.50.21 -p 80 -e "/onvif/device_service" -m "/onvif/media_service"

[520913/520913] main:784 - Start !!! (192.168.50.21:80, admin:888888, device_url_path: /onvif/device_service, media_url_path: /onvif/media_service)
[520913/520914] soap_http_access:230 - (request: <?xml version='1.0' encoding='utf-8'?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema"><SOAP-ENV:Body><tds:GetDeviceInformation /></SOAP-ENV:Body><SOAP-ENV:Header><Security SOAP-ENV:mustUnderstand="1" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2022-11-11T16:37:31.000Z</Created><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">09kyyeZdoex3cvaKyE0pjP8Re04=</Nonce><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">zjFpKDIo+V+ly5RNe/JrtZneL2M=</Password></UsernameToken></Security></SOAP-ENV:Header></SOAP-ENV:Envelope>
)
[520913/520914] http_request_soap:248 - enter (soap_req->h_action: (null))
*   Trying 192.168.50.21:80...
* Connected to 192.168.50.21 (192.168.50.21) port 80 (#0)
> POST /onvif/device_service HTTP/1.1
Host: 192.168.50.21
Accept: */*
Content-Type: application/soap+xml; charset=utf-8
Accept-Encoding: gzip, deflate
Content-Length: 1012

* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: application/soap+xml; charset=utf-8
< Connection: close
< Content-Length: 659
<
* Closing connection 0
[520913/520914] http_request_soap:325 - ret: 0,
[520913/520914] soap_http_access:236 - (response: <?xml version="1.0" encoding="utf-8" standalone="yes" ?><s:Envelope xmlns:sc="http://www.w3.org/2003/05/soap-encoding" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery"><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value>ter:NotAuthorized</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en">Sender not Authorized. Invalid username or password! You still have 27 attempt(s).</s:Text></s:Reason></s:Fault></s:Body></s:Envelope>)
[520913/520914] qtask_GetDeviceInformation:197 - No support !!! (http://192.168.50.21:80/onvif/device_service)

[520913/520913] main:820 - exit
[520913/520913] app_exit:647 - exit
```
#### B. with pass
```
$ ./onvif_client_123 -d3 -i 192.168.50.21 -p 80 -u admin -s admin -e "/onvif/device_service" -m "/onvif/media_service"

[520915/520915] main:784 - Start !!! (192.168.50.21:80, admin:admin, device_url_path: /onvif/device_service, media_url_path: /onvif/media_service)
[520915/520916] qtask_GetDeviceInformation:187 - (gid:769.0, Manufacturer: General)
[520915/520916] qtask_GetDeviceInformation:188 - (gid:769.0, Model: IP Camera)
[520915/520916] qtask_GetDeviceInformation:189 - (gid:769.0, FirmwareVersion: 2.400.0000.16.R, Build Date 2017-08-31)
[520915/520916] qtask_GetDeviceInformation:190 - (gid:769.0, SerialNumber: 2L066D7PAG00031)
[520915/520916] qtask_GetDeviceInformation:191 - (gid:769.0, HardwareId: 1.00)

[ubuntu-x86-RELEASE@msi-vbx utilx9]$

```

**Comment by lankahsu520** [comment]
I removed the default user/pass.

static char srv_user[LEN_OF_USER]="";
static char srv_pass[LEN_OF_PASS]="";

and try ./onvif_client_123 -d4
to get more debug messages.

```log
[504239/504240] soap_http_access:230 - (request:
[504239/504240] soap_http_access:236 - (response:
```

**Comment by mkaufer** [comment]
After removing the default user/pass I get the same output. This leads me to believe that the issue is something to do with the way the authorization works. 
This is the output from the getDeviceInformation with -d4:

[0;37m[1662381/1662383] soap_http_access:230 - (request: <?xml version='1.0' encoding='utf-8'?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema"><SOAP-ENV:Body><tds:GetDeviceInformation /></SOAP-ENV:Body><SOAP-ENV:Header><Security SOAP-ENV:mustUnderstand="1" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2022-11-14T08:32:36.000Z</Created><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">Kb9GoQM/UoeHVYWr+lhj8USvkP0=</Nonce><Username></Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">d8DpeBRBUdCYWa7vT8I1XMDwW3w=</Password></UsernameToken></Security></SOAP-ENV:Header></SOAP-ENV:Envelope>
)[0m
[0;37m[1662381/1662383] http_request_soap:248 - enter (soap_req->h_action: (null))[0m
[0;37m[1662381/1662383] http_request_soap:325 - ret: 0, [0m
[0;37m[1662381/1662383] soap_http_access:236 - (response: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 401 &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;meta charset=&quot;UTF-8&quot; /&gt;&lt;title&gt;Error&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;h1&gt;401 Unauthorized.&lt;/h1&gt;&lt;/body&gt;&lt;/html&gt;</title>
</head>
<body><h2>HTTP ERROR 401 &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;meta charset=&quot;UTF-8&quot; /&gt;&lt;title&gt;Error&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;h1&gt;401 Unauthorized.&lt;/h1&gt;&lt;/body&gt;&lt;/html&gt;</h2>
<table>
<tr><th>URI:</th><td>/onvif/device_service</td></tr>
<tr><th>STATUS:</th><td>401</td></tr>
<tr><th>MESSAGE:</th><td>&lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;meta charset=&quot;UTF-8&quot; /&gt;&lt;title&gt;Error&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;h1&gt;401 Unauthorized.&lt;/h1&gt;&lt;/body&gt;&lt;/html&gt;</td></tr>
<tr><th>SERVLET:</th><td>-</td></tr>
</table>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.30.v20200611</a><hr/>

</body>
</html>
)[0m
[0;32;31m[1662381/1662383] qtask_GetDeviceInformation:197 - No support !!! (http://192.168.2.113:80/onvif/device_service)[0m

I have also attached the full output from ./onvif_client_123 -d4. This is the output with no user/pass but even when I run it with the user/pass the output is almost identical.

[onvif_client_output.txt](https://github.com/lankahsu520/utilx9/files/10003520/onvif_client_output.txt)

**Comment by lankahsu520** [comment]
Could you try to use "ONVIF Device Manage" ?

I wrote these codes with the logs from "Wireshark" + "ONVIF Device Manage".
And use curl + xml files.

Maybe you can try.

**Comment by lankahsu520** [comment]
HTTP ERROR 401,
The is a WEB error (HTTP digest), not onvif error (SOAP) !

Some cameras can be disabled(HTTP digest)) on ONVIF.

I updated some codes, please git pull.

To enable checking HTTP Auth
./onvif_client_123 -d4 -a

**Comment by mkaufer** [comment]
Unfortunately that did not work, I get the exact same output back. 

Also after I did a git pull I had to add "int http_auth" to utilx9.h under the OnvifX_STRUCT definition for it to be able to compile. Was this supposed to be the case or did I perhaps do something wrong?

I know that the device I am connecting to has everything enabled since I am able to get this to work with "Onvif Device Manager" on my windows machine and am able to use the github library "python-onvif2-zeep" to also get the information. 

Do you have any ideas as to why the HTTP would be throwing an error? Could this be a conflict between different libraries that I have installed. I downloaded all the libraries in the readme excluding libyuarel.

**Comment by lankahsu520** [comment]
I fixed OnvifX_STRUCT.
And we can use curl
[helper_ONVIF.md](https://github.com/lankahsu520/HelperX/blob/master/helper_ONVIF.md)

You can use "wireshark" + "Onvif Device Manager" to grap the *.xml (such as GetCapabilities.xml, GetDeviceInformation.xml,... ).
or use gsoap to generate.

**Comment by mkaufer** [comment]
I used wireshark and was able to pull this xml from it.

<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"><s:Header><a:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</a:Action><a:MessageID>uuid:0c585f38-470b-4b77-a038-6a5a3978b94e</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To></s:Header><s:Body><Probe xmlns="http://schemas.xmlsoap.org/ws/2005/04/discovery"><d:Types xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dp0="http://www.onvif.org/ver10/network/wsdl">dp0:NetworkVideoTransmitter</d:Types></Probe></s:Body></s:Envelope>  
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"><s:Header><a:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</a:Action><a:MessageID>uuid:0c585f38-470b-4b77-a038-6a5a3978b94e</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To></s:Header><s:Body><Probe xmlns="http://schemas.xmlsoap.org/ws/2005/04/discovery"><d:Types xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dp0="http://www.onvif.org/ver10/network/wsdl">dp0:NetworkVideoTransmitter</d:Types></Probe></s:Body></s:Envelope>  

<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"><s:Header><a:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</a:Action><a:MessageID>uuid:dd85789d-205d-4305-b0ed-3344aed146f7</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To></s:Header><s:Body><Probe xmlns="http://schemas.xmlsoap.org/ws/2005/04/discovery"><d:Types xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dp0="http://www.onvif.org/ver10/network/wsdl">dp0:NetworkVideoDisplay</d:Types></Probe></s:Body></s:Envelope>  
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"><s:Header><a:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</a:Action><a:MessageID>uuid:0c585f38-470b-4b77-a038-6a5a3978b94e</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To></s:Header><s:Body><Probe xmlns="http://schemas.xmlsoap.org/ws/2005/04/discovery"><d:Types xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dp0="http://www.onvif.org/ver10/network/wsdl">dp0:NetworkVideoTransmitter</d:Types></Probe></s:Body></s:Envelope>

<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"><s:Header><a:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</a:Action><a:MessageID>uuid:dd85789d-205d-4305-b0ed-3344aed146f7</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To></s:Header><s:Body><Probe xmlns="http://schemas.xmlsoap.org/ws/2005/04/discovery"><d:Types xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dp0="http://www.onvif.org/ver10/network/wsdl">dp0:NetworkVideoDisplay</d:Types></Probe></s:Body></s:Envelope>

<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"><s:Header><a:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</a:Action><a:MessageID>uuid:e0b0f451-7f11-451b-99cd-a91cef38a2cc</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To></s:Header><s:Body><Probe xmlns="http://schemas.xmlsoap.org/ws/2005/04/discovery"><d:Types xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dp0="http://www.onvif.org/ver10/device/wsdl">dp0:Device</d:Types></Probe></s:Body></s:Envelope>

<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"><s:Header><a:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</a:Action><a:MessageID>uuid:e0b0f451-7f11-451b-99cd-a91cef38a2cc</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To></s:Header><s:Body><Probe xmlns="http://schemas.xmlsoap.org/ws/2005/04/discovery"><d:Types xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dp0="http://www.onvif.org/ver10/device/wsdl">dp0:Device</d:Types></Probe></s:Body></s:Envelope>

<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"><s:Header><a:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</a:Action><a:MessageID>uuid:dd85789d-205d-4305-b0ed-3344aed146f7</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To></s:Header><s:Body><Probe xmlns="http://schemas.xmlsoap.org/ws/2005/04/discovery"><d:Types xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dp0="http://www.onvif.org/ver10/network/wsdl">dp0:NetworkVideoDisplay</d:Types></Probe></s:Body></s:Envelope>

<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"><s:Header><a:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</a:Action><a:MessageID>uuid:e0b0f451-7f11-451b-99cd-a91cef38a2cc</a:MessageID><a:ReplyTo><a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To></s:Header><s:Body><Probe xmlns="http://schemas.xmlsoap.org/ws/2005/04/discovery"><d:Types xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dp0="http://www.onvif.org/ver10/device/wsdl">dp0:Device</d:Types></Probe></s:Body></s:Envelope>

I know that valgrind is useful for debugging but is it necessary to have it installed? I don't have it installed so I took out that command and just run ../onvif_pass_123 but that causes a segmentation fault in onvif_pass_123.

**Comment by lankahsu520** [comment]
Yes, I got "segmentation fault" and try to use valgrind.
But no useful for debugging. ( SHA1_Init causes this. )

I fixed this bug !

**Comment by lankahsu520** [comment]
from your xml, You don't have ONVIF AUTH.
Try
#### A. HTTP AUTH

```bash
$ curl -u ${USER}:${PASSWORD}

$ curl --digest -u ${USER}:${PASSWORD}
```

####

**Comment by mkaufer** [comment]
Thanks for the fix! Unfortunately that didn't solve the issue and I still get the same output.

The xml was from OnvifDeviceManager application on Windows using Wireshark to capture it and not from what I've been doing in code. Can you think of a reason that this xml is the only traffic that came across Wireshark while using OnvifDeviceManager?

I have tried to get the authentication working with the onvif_client.sh but am not having any luck. I read that the Time could cause authentication errors but I checked and the time on the http request matches the device so I don't think that is the issue.

I pulled a trace of the curl and have attached it. I edited the xml from how it originally was, trying different methods I have come across from "Onvifs Application Programmers Guide" as well as many different stack overflow posts. Looking through the trace I do not see anything that would be causing this issue. Can you take a look and see if something is off?

[onvif_client_output.txt](https://github.com/lankahsu520/utilx9/files/10071362/onvif_client_output.txt)

**Comment by lankahsu520** [comment]
I prefer to use curl. We can see HTTP Header & HTTP Body on logs. It is easily to debug.

You also need to make sure HTTP Header is correct.
Some web servers won't allow "User-Agent: xxx" or must have some flags.

In xml, will \<MessageID\>, \<ReplyTo\> or others be needed ? 

```bash
[curl -v  -u admin:admin -H 'Content-Type: application/soap+xml; charset=utf-8' -H 'Accept-Encoding: gzip, deflate' -d @./GetProfiles-auth-req.xml http://192.168.50.21/onvif/media_service ]
*   Trying 192.168.50.21:80...
* Connected to 192.168.50.21 (192.168.50.21) port 80 (#0)
* Server auth using Basic with user 'admin'
> POST /onvif/media_service HTTP/1.1
> Host: 192.168.50.21
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.86.0
> Accept: */*
> Content-Type: application/soap+xml; charset=utf-8
> Accept-Encoding: gzip, deflate
> Content-Length: 1033
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/soap+xml; charset=utf-8
< Connection: close
< Content-Length: 7905
<

```

**Comment by lankahsu520** [comment]
close it.
